urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = [
       url('^$', views.index, name='index'),
       url('^checkout$', views.checkout, name='checkout'),
       url('^checkout/delete/([0-9]+)$', views.delete, name='cartdelete'),
       url('^cart/change$', views.changeQuantity, name='cartchange'),
       url('^cart/add$', views.addToCart, name='addtocart'),
       #url('^checkout/change/(?P<product_id>-?\d+)/(?P<quantity>-?\d+)$', views.changeQuantity, name='cartchange'),
       url('^shipping$', views.shipping, name='shipping'),
       url('^shipping/delete', views.delete_shipping, name='delete_shipping'),
       url('^charge/', views.charge, name='charge'),
       url('^products$', views.listing, name='products'),
       url('^products/cat/(?P<category>[\w-]+)$', views.listing_category, name='productscat'),
       url('^products/([0-9]+)$', views.product_detail, name='products'),
       ]

models.py
from __future__ import unicode_literals
from datetime import date

from django.db import models
from django import forms
from easy_thumbnails.fields import ThumbnailerImageField
from django.contrib.auth.models import User

from models_products import *
from models_shipping import *

class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    #valid_products = models.ManyToManyField(Product)
    amount_off = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    currency = models.CharField(default="USD", max_length=50)
    expires = models.DateField(blank=True, null=True)
    valid = models.BooleanField(default=True)
    max_redemptions = models.IntegerField(blank=True, null=True)
    times_redeemed = models.IntegerField(default=0)
    @property
    def is_expired(self):
        if self.expires is not None and date.today() > self.expires:
            return True
        return False
    @property
    def none_left(self):
        if self.max_redemptions is not None and self.times_redeemed >= self.max_redemptions:
            return True
        return False
    def __unicode__(self):
        return "%s - %s (%s/%s)" % (self.code, self.amount_off, self.times_redeemed, self.max_redemptions)

class Order(models.Model):
    class Meta:
        ordering = ['-created']
    user = models.ForeignKey(User, null=True)
    shipping_address =  models.CharField(max_length=500, null=True, blank=True)
    shipping_email =  models.CharField(max_length=100, null=True, blank=True)
    shipped_status = models.BooleanField(default=False)
    delivered_status = models.BooleanField(default=False)
    tracking = models.CharField(max_length=50, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    coupon = models.CharField(max_length=50, null=True, blank=True)
    discount = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    shipping_cost = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    tax = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    @property
    def subtotal(self):
        subtotal = 0
        for productorder in self.productorder_set.all():
            subtotal = subtotal + productorder.total()
        return subtotal
    @property
    def total(self):
        subtotal = self.subtotal
        total = subtotal + self.shipping_cost + self.tax - self.discount
        return total
    @property
    def stripe_total(self):
        return self.total * 100
    def __unicode__(self):
        return "Order ID #%s - %s" % (self.pk, self.user)

class ProductOrder(models.Model):
    order = models.ForeignKey(Order)
    #product = models.ForeignKey(Product)
    product_log = models.CharField(max_length=500, null=True, blank=True)
    accessories = models.CharField(max_length=500, null=True, blank=True)
    options = models.CharField(max_length=500, null=True, blank=True)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    def total(self):
        return self.price * self.quantity
    def __unicode__(self):
        return "Order ID #%s - %s" % (self.order.pk, self.product_log)

views.py
from __future__ import division

from django.shortcuts import render_to_response,  get_object_or_404, redirect
from django.template.context import RequestContext

import stripe
from models import *

from views_utils import *
from views_browse import *
from views_cart import *
from views_checkout import *
from views_process_order import *

# The Store Homepage
def index(request):
    products = Product.objects.filter(listed=True)[:6]
    features = Feature.objects.all()
    categories = Category.objects.all()[:10]
    args = {
        'products': products,
        'features': features,
        'categories': categories,
    }
    return render_to_response('store/index.html', RequestContext(request,args))

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>
{% block title %}
Template Site
{% endblock %}
</title>
{% block head %}
    {% include 'base/head.html' %}
{% endblock %}
</head>
<body>
{% block navbar %}
    {% include 'base/navbar.html' %}
{% endblock %}
{% block content %}

{% endblock %}
{% block modal %}

{% endblock %}
{% block footer %}
    {% include 'base/footer.html' %}
{% endblock %}
{% block js %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}
</body>
</html>

templates/base/footer.html
<!-- Footer -->
<hr>

<div class="container">
     <!-- Footer -->
     <footer>
         <div class="row">
             <div class="col-lg-12">
                 <p>Powered By <a href = "http://www.code.coop">The Code Cooperative &copy; 2016</a></p>
             </div>
         </div>
     </footer>
</div>

templates/base/head.html
{% load staticfiles %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/main.css' %}" rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<script src="js/respond.min.js"></script>
<![endif]-->
<link rel="shortcut icon" href="images/ico/favicon.ico">

templates/base/navbar.html
{% load staticfiles %}
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'store:index' %}">Template Site</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
            </ul>
            {% include 'base/navbar-right.html' %}
        </div>
    </div>
    <!-- /.container -->
</nav>

templates/profile/ordersummary.html
<h2>Orders</h2>
{% for order in request.user.order_set.all %}
Order Created: {{ order.created }}
Ship to: {{ order.shipping_address }}
<table class="table table-condensed">
    <thead>
        <th>Product Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
    </thead>
    {% for productorder in order.productorder_set.all %}
    <tr>
        <td>{{ productorder.product_log }}</td>
        <td>${{ productorder.price }}</td>
        <td>{{ productorder.quantity }}</td>
        <td>${{ productorder.total }}</td>
    </tr>
    {% endfor %}
    <tr>
        <td>Subtotal:</td>
        <td></td>
        <td></td>
        <td>${{ order.subtotal }}</td>
    </tr>
    <tr>
        <td><em>Discount ({{ order.coupon }})</em></td>
        <td></td>
        <td></td>
        <td><em>-${{ order.discount }}</em></td>
    </tr>
    <tr>
        <td><strong>Total</strong></td>
        <td></td>
        <td></td>
        <td><strong>${{ order.total }}</strong></td>
    </tr>
</table>
<hr>
{% endfor %}

templates/profile/shipping.html
<h2>Shipping Info</h2>
<ul class="list-unstyled">
    <li>{{ request.user.first_name }} </li>
    <li>{{ request.user.shipping.address }}</li>
    <li>{{ request.user.shipping.city }}, {{ request.user.shipping.state }}</li>
</ul>

templates/store/base.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block head %}
    {{ block.super }}
    <link href="{% static 'store/css/shop-homepage.css' %}" rel="stylesheet">
    <link href="{% static 'store/css/main.css' %}" rel="stylesheet">
    <!-- Will likely not need these -->
    <link href="{% static 'store/css/font-awesome.min.css' %}" rel="stylesheet">
{% endblock %}
{% block navbar %}
    {% include 'store/navbar.html' %}
{% endblock %}
{% block content %}
{% endblock %}
{% block js %}
    {{ block.super }}
    <!--<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>-->
{% endblock %}

templates/store/buttons/paypal_button.html
{% load staticfiles %}
    <!-- delete 'data-env' to make legit payments -->
    <script src="{% static 'store/js/paypal-button.min.js' %}?merchant={{ paypal_merchant_id }}"
        data-env="sandbox"
        data-button="buynow"
        data-name="Template Site Checkout"
        data-amount="{{ request.session.total }}"
        async
        ></script>

templates/store/buttons/stripe_button.html
{% load staticfiles %}
<form action="{% url 'store:charge' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="cc-amount" value="{% widthratio request.session.total 1 100 %}">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ stripe_pub_key }}"
    data-name="Demo Site"
    data-amount="{% widthratio request.session.total 1 100 %}"
    data-description="Template Site's Charge Card"
    data-image="{% static 'store/images/stripe_128x128.png' %}"
    data-locale="auto">
  </script>
</form>

templates/store/checkout.html
{% extends "store/base.html" %}
{% load staticfiles %}
{% load get_item %}
{% block head %}
{{ block.super }}
<link href="{% static 'store/css/checkout_products.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<section id="cart_items">
	<div class="container">
		{% include 'store/checkout_shipping.html' %}
		<div class="review-payment">
			<h3>Review & Payment</h3>
		</div>
		{% include 'store/checkout_products.html' %}
		{% if request.session.total > 1 and shipping %}
		<div class="payment-options pull-right">
		    <ul class="list-inline">
		        <li>
					{% include 'store/buttons/stripe_button.html' %}
				</li>
			</ul>
		</div>
		{% endif %}
	</div>
</section>
{% endblock %}
{% block js %}
	{{ block.super}}
	<script src="{% static 'store/js/checkout_products.js' %}"></script>

	<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
	<script type="text/javascript" src="{% static 'store/js/stripe.js' %}"></script>
{% endblock %}

templates/store/checkout_products.html
{% load thumbnail %}
{% load staticfiles %}
{% load get_item %}

<style media="screen">
  @-moz-document url-prefix() {
fieldset { display: table-cell; }
}
</style>
{% if products %}
<div class="table-responsive cart_info">
    <table class="table">
        <thead>
            <tr class="cart_menu">
                <td class="image">Item</td>
                <td class="description"></td>
                <td class="price">Price</td>
                <td class="quantity">Quantity</td>
                <td class="total">Total</td>
                <td class="cart_delete pull-right"></td>
            </tr>
        </thead>
        <tbody>
            {% for item in products %}
            <tr>
                <td class="image">
                    <a href="{% url 'store:products' item.product.pk %}"><img src="{% thumbnail item.product.mainimage 200x200 %}" alt=""></a>
                </td>
                <td class="description">
                    <h4><a href="{% url 'store:products' item.product.pk %}">{{ item.product.title }}</a></h4>
                    <p>Product ID: {{ item.product.pk }}</p>
                    {% if item.accessories %}
                        <ul class ="list-unstyled">
                        <strong>Accessories: </strong>
                            {% for accessory in item.accessories %}
                            <li>{{ accessory.title }}: ${{ accessory.price}}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% if item.options %}
                    <ul class ="list-unstyled">
                    <strong>Options: </strong>
                        {% for option in item.options %}
                            <li>{{ option.title }}: ${{ option.price }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {% if item.product.status = "preorder" %}
                    <span style="color:red">This item is currently out of stock, preorders can take a while to process</span>
                    {% endif %}
                </td>
                <td class="price">
                    <p>${{ item.price }}</p>
                </td>
                <td class="quantity cart_quantity">
                    <div class="cart_quantity_button">
                        <form action="{% url 'store:cartchange' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" value="{{ forloop.counter0 }}" name="item_id" />
                            <input class="cart_quantity_input" type="text" name="quantity" value="{{ item.session.quantity }}" autocomplete="off" size="2">
                        </form>
                    </div>
                </td>
                <td class="total cart_total">
                    <p class="cart_total_price">${% widthratio item.price 1 item.session.quantity %}</p>
                </td>
                <td class="cart_delete">
                    <a class="cart_quantity_delete" href="{% url 'store:cartdelete' forloop.counter0 %}"><i class="fa fa-times"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<div class="table-responsive pull-right">
  <table>
    <tr>
        <td colspan="4">&nbsp;</td>
        <td colspan="2">
            <table class="table table-condensed total-result">
                <tr>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% if coupon_result != None %}
                        RESULT: {% if coupon_result %} Valid Coupon {% else %} Invalid Coupon {% endif %}
                        {% endif %}
                        <td><label for="coupon_code">Coupon Code</label></td>
                        <td><input id="coupon_code" type="text" name="coupon_code" value="" autocomplete="off"></td>
                    </form>
                </tr>
                <tr>
                    <td>Cart Sub Total</td>
                    <td>${{ request.session.subtotal }}</td>
                </tr>
                <tr class="shipping-cost">
                    <td>Shipping Cost</td>
                    <td>Free</td>
                </tr>
                {% if request.session.coupon|get_item:'amount' != None %}
                <tr class="discount">
                    <td>Discount</td>
                    <td>-${{ request.session.coupon|get_item:'amount' }}</td>
                </tr>
                {% endif %}
                <tr>
                    <td>Total</td>
                    <td><span>${{ request.session.total }}</span></td>
                </tr>
            </table>
        </td>
    </tr>
  </table>
</div>
{% else %}
<div class="container">
    <h2> There are no items currently in the cart.</h2>
</div>
{% endif %}

templates/store/checkout_shipping.html
{% load thumbnail %}
{% load staticfiles %}
{% load get_item %}
<div class="container">

<div class="step-one">
    <h2 class="heading">Shipping Address</h2>
</div>
<div class="checkout-options">
    <div class="row">
    {% if shipping %}
    <form action="{% url 'store:shipping' %}" method="POST">
        {% csrf_token %}
        <div class= "col-md-5">
            <address>
                <strong>{{ shipping.name }}</strong><br>
                {{ shipping.address }}<br>
                {{ shipping.city }}, {{ shipping.state }} {{ shipping.postal_code }}<br>
                <em>{{ shipping.email }}</em>
            </address>
        </div>
    </form>
    <form action="{% url 'store:delete_shipping' %}"> <input type="submit" value="Delete Shipping" /> </form>
    {% else %}
        <form action="{% url 'store:shipping' %}" method="POST">
            {% csrf_token %}
            <fieldset>
                  {% for field in shippingform %}
                      {% if field.errors %}
                          <div class="control-group error col-sm-4">
                              <label class="control-label">{{ field.label }}</label>
                              <div class="controls">{{ field }}
                                  <span class="help-inline">
                                      {% for error in  field.errors %}{{ error }}{% endfor %}
                                  </span>
                              </div>
                          </div>
                      {% else %}
                          <div class="control-group col-sm-4">
                              <label class="control-label">{{ field.label }}</label>
                              <div class="controls">{{ field }}
                                  {% if field.help_text %}
                                      <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                  {% endif %}
                              </div>
                          </div>
                      {% endif %}
                      {% if forloop.counter|divisibleby:2 %}
                        <hr class="visible-xs" />
                      {% endif %}
                  {% endfor %}
              </fieldset>
              <br />
              <div class="form-actions col-sm-4">
                  <button type="submit" class="btn btn-primary" >Submit</button>
              </div>
          </form>
    {% endif %}
    </div>
</div><!--/checkout-options-->

</div>

templates/store/index.html
{% extends "store/base.html" %}
{% load thumbnail %}
{% load staticfiles %}
{% block content %}
<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-md-3">
            <div class="list-group">
              {% if categories|length > 0 %}
                {% for category in categories %}
                <a href="{% url 'store:productscat' category.slug %}" class="list-group-item">{{ category.title }}</a>
                {% endfor %}
              {% endif %}
            </div>
        </div>
        <div class="col-md-9">

            <div class="row">
                {% for product in products %}
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <a href="{% url 'store:products' product.pk %}">
                            <img src="{% thumbnail product.mainimage 300x150 crop %}" alt="{{ product.title }}">
                        </a>
                        <div class="caption">
                            <h4 class="pull-right">${{product.total}}</h4>
                            <h4><a href="{% url 'store:products' product.pk %}">{{product.title}}</a>
                            </h4>
                            <p>{{ product.description|safe }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

        </div>

    </div>

</div>
<!-- /.container -->
{% endblock %}

templates/store/navbar-right.html
<ul class ="nav navbar-nav navbar-right">
    {% if request.user.is_authenticated %}
    <li class="dropdown">
        <a href="#" class="navbar-brand dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ request.user.username|title }} <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="/admin/logout/">Log Out</a></li>
            {% if request.user.is_superuser or request.user.is_staff %}
                <li class = "divider"></li>
                <li><a href="/admin/">Admin</a></li>
                <li><a href="/api-view/">REST API</a></li>
            {% endif %}
        </ul>
    </li>
  {% else %}
  <li>
      <a href="/admin">Login</a>
  </li>
  {% endif %}
</ul>

<!-- /.navbar-collapse -->

templates/store/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'store:index' %}">E-Commerce Site</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'store:index' %}">Store Front</a>
                </li>
                <li>
                    <a href="{% url 'store:products' %}">Products</a>
                </li>
                <li>
                    <a href="{% url 'store:checkout' %}">Checkout
                        {% if request.session.cart|length > 0 %}
                        ({{ request.session.cart|length }})
                        {% endif %}
                    </a>
                </li>
            </ul>
            {% include 'store/navbar-right.html' %}
        </div>

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->

</nav>

templates/store/order-complete.html
{% extends "store/base.html" %}
{% load thumbnail %}
{% load staticfiles %}
{% load get_item %}
{% block content %}
	<div class="container">
		<h1> {{ cc_result }}</h1>
	</div>
	Order Created: {{ order.created }}
	Ship to: {{ order.shipping_address }}
	<table class="table table-condensed">
	    <thead>
	        <th>Product Name</th>
	        <th>Price</th>
	        <th>Quantity</th>
	        <th>Total</th>
	    </thead>
	    {% for productorder in order.productorder_set.all %}
	    <tr>
	        <td>{{ productorder.product_log }}</td>
	        <td>${{ productorder.price }}</td>
	        <td>{{ productorder.quantity }}</td>
	        <td>${{ productorder.total }}</td>
	    </tr>
	    {% endfor %}
	    <tr>
	        <td>Subtotal:</td>
	        <td></td>
	        <td></td>
	        <td>${{ order.subtotal }}</td>
	    </tr>
	    <tr>
	        <td><em>Discount ({{ order.coupon }})</em></td>
	        <td></td>
	        <td></td>
	        <td><em>-${{ order.discount }}</em></td>
	    </tr>
	    <tr>
	        <td><strong>Total</strong></td>
	        <td></td>
	        <td></td>
	        <td><strong>${{ order.total }}</strong></td>
	    </tr>
	</table>
	<hr>
{% endblock %}
{% block js %}
	{{ block.super}}
	<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
	<script type="text/javascript" src="{% static 'store/js/stripe.js' %}"></script>
{% endblock %}

templates/store/product-details.html
{% extends "store/base.html" %}
{% load thumbnail %}
{% load staticfiles %}
{% block content %}
<!-- Page Content -->
<div class="container">

<div class="product_detail">

<!-- Portfolio Item Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{{ product.title }}
            <small>{% if product.subtitle %}{{ product.subtitle }}{% endif %}</small>
        </h1>
    </div>
</div>
<!-- /.row -->

<!-- Portfolio Item Row -->
<div class="row">
    <div class="col-md-8">
        <img class="img-responsive" src="{% thumbnail product.mainimage 1200x1200 %}" alt="{{ product.title }}">
    </div>
    <div class="col-md-4">
    <h3>{{ product.title }}</h3>
    {% if product.description|length > 0 %}
        {{ product.description|safe }}
    {% else %}
        {% lorem 100 w random %}
    {% endif %}
    <hr />
    {% if product.listed %}
    <form id="shopping_cart" action="{% url 'store:addtocart' %}" method="POST">
        {% csrf_token %}
    {% if optioncategories %}
    {% for category in optioncategories %}
    <h4>{{ category.title }}</h4>
    <select name="options" >
        {% for option in category.option_set.all %}
        <option value="{{ option.pk }}" form="shopping_cart">{{ option.title }}: ${{ option.price }}</option>
        {% endfor %}
    </select>
    {% endfor %}
    <hr />
    {% endif %}
    {% if product.accessories %}
    {% for accessory in product.accessories.all %}
    {% if accessory.status != "outofstock" %}
    <input checked type="checkbox" name="accessories" value="{{ accessory.pk }}">{{ accessory.title }} ${{ accessory.price }}<br>
    {% endif %}
    {% endfor %}
    <hr />
    {% endif %}
	${{ product.total }} {% if product.price != product.total %}<strike style="color:red">${{ product.price }}</strike>{% endif %}</p>
    {% if product.status == "outofstock" %}
        Out of Stock
    {% else %}
        {% if product.status == "preorder" %}
            <span style="color:red">No more items in stock. Feel free to preorder, though.</span>
        {% endif %}
        {% if product.status == "instock" %}
            <strong>{{ product.stock }} items left</strong>
        {% endif %}
            <label>Quantity:</label>
            <input type="hidden" value="{{ product.pk }}" name="item_id" />
            <button type="submit" class="btn btn-fefault cart">
                <i class="fa fa-shopping-cart"></i>
                Add to cart
            </button>
        </form>
        {% endif %}
    {% endif %}
    </div>
</div>
<!-- /.row -->
<hr />
<div class="row">
    {% for image in product.images.all %}
    <div class="col-md-3">
        <img class="img-responsive" src="{% thumbnail image.image 400x400 %}" alt="{{ product.title }}">
    </div>
    {% endfor %}
</div class = "row">
</div>

<!-- Related Projects Row -->
<div class="row">

    <div class="col-lg-12">
        <h3 class="page-header">Related Products</h3>
    </div>
	{% for related_product in related_products %}
    <div class="col-sm-3 col-xs-6">
		<h4>{{ related_product.title }}</h4>
        <a href="{% url 'store:products' related_product.pk %}">
            <img class="img-responsive portfolio-item" src="{% thumbnail related_product.mainimage 500x300 %}" alt="{{ related_product.title }}">
        </a>
    </div>
	{% endfor %}

</div>
<!-- /.row -->
</div>

{% endblock %}

templates/store/shop.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block navbar %}
{% include 'store/navbar.html' %}
{% endblock %}
{% block content %}
<!-- Page Content -->
<div class="container">

    <!-- Page Header -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Products
                <small>See Everything For Sale</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Projects Row -->
    <div class="row">
    {% for product in products %}
        <div class="col-md-4 portfolio-item">
            <a href="{% url 'store:products' product.pk %}">
                <img class="img-responsive" src="{% thumbnail product.mainimage 700x400 crop %}" alt="{{ product.title }}">
            </a>
            <h3>
                <a href="{% url 'store:products' product.pk %}">{{ product.title }}</a>
                <small>${{ product.total }} {% if product.price != product.total %}<strike style="color:red">${{ product.price }}</strike>{% endif %}</small>
            </h3>
            <p>
              {% if product.description|length > 0 %}
                {{ product.description|safe }}
              {% else %}
                This product does not have a description yet.
              {% endif %}
            </p>
        </div>
    {% if forloop.counter|divisibleby:3 %}
    </div>
    <div class="row">
    {% endif %}
    {% endfor %}
    </div>
    <!-- /.row -->

    <hr>

    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a href="?page={{ products.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ products.number }} of {{ products.paginator.num_pages }}.
            </span>

            {% if products.has_next %}
                <a href="?page={{ products.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
</div>
<!-- /.container -->
{% endblock %}